# Generated by Django 2.1.5 on 2019-01-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('timmar', models.IntegerField(default=0)),
                ('projektnr', models.IntegerField(default=1900)),
                ('arbetsplats', models.CharField(max_length=60)),
                ('kund', models.CharField(max_length=60)),
                ('arbete', models.BooleanField()),
                ('sjuk', models.BooleanField()),
                ('tidbank', models.BooleanField()),
            ],
        ),
    ]
