# Generated by Django 2.1.5 on 2019-02-05 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbetsplats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arbetsplats_namn', models.CharField(default='', max_length=100, verbose_name='Arbetsplats')),
            ],
            options={
                'verbose_name_plural': 'Arbetsplatser',
            },
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projektnr', models.CharField(max_length=100, verbose_name='Beskrivning')),
                ('arbetsplats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tid_rapport.Arbetsplats')),
            ],
            options={
                'verbose_name_plural': 'Projekt',
            },
        ),
        migrations.CreateModel(
            name='Tid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar', models.IntegerField(default=2019, verbose_name='År')),
                ('vecka', models.IntegerField(default=1, verbose_name='Vecka')),
                ('mon', models.IntegerField(default=0, verbose_name='Måndag')),
                ('tis', models.IntegerField(default=0, verbose_name='Tisdag')),
                ('ons', models.IntegerField(default=0, verbose_name='Onsdag')),
                ('tors', models.IntegerField(default=0, verbose_name='Torsdag')),
                ('fre', models.IntegerField(default=0, verbose_name='Fredaq')),
                ('lor', models.IntegerField(default=0, verbose_name='Lördag')),
                ('son', models.IntegerField(default=0, verbose_name='Söndag')),
                ('trakt', models.IntegerField(default=0, verbose_name='Trakt')),
                ('projektnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tid_rapport.Projekt', verbose_name='Beskrivning')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Användare')),
            ],
            options={
                'verbose_name_plural': 'Tider',
            },
        ),
    ]
