# Generated by Django 2.1.5 on 2019-01-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tid_rapport', '0002_auto_20190111_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbetsplats',
            name='arbetsplats_kontakt_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='arbetsplats',
            name='arbetsplats_telefonnr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kund',
            name='kund_telefonnr',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
